apiVersion: v1
kind: ConfigMap
metadata:
  name: security-context-config
data:
  podSecurityContext: |
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext: |
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      add:
        - NET_BIND_SERVICE
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
